apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: quingo-app
type: Opaque
stringData:
  MAIN_SERVICE_HOST: quingo-main-service-service
  AUTH_SERVICE_HOST: auth-service-service