apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: quingo-app
type: Opaque
stringData:
  MAIN_SERVICE_HOST: quingo-main-service-service
  AUTH_SERVICE_HOST: auth-service-service
  CORS_ALLOWED_ORIGINS: "https://quingo.arhr.tech,https://docs-quingo.arhr.tech,http://localhost:5173,http://localhost:5173/,http://localhost"
