spring:
  application:
    name: gateway

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${CORS_ALLOWED_ORIGINS}
                  - "https://quingo.arhr.tech"
                  - "https://docs-quingo.arhr.tech"
                  - "http://localhost"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders:
                  - "*"
                allowCredentials: true
                maxAge: 3600
          routes:
            - id: auth-route
              uri: http://${AUTH_SERVICE_HOST}
              predicates:
                - Path=/api/auth/**

            - id: quizzes-route
              uri: http://${MAIN_SERVICE_HOST}
              predicates:
                - Path=/api/quizzes/**

            - id: catalog-route
              uri: http://${MAIN_SERVICE_HOST}
              predicates:
                - Path=/api/catalog/**

            - id: users-route
              uri: http://${MAIN_SERVICE_HOST}
              predicates:
                - Path=/api/users/**

auth-service:
  public-key-url: http://${AUTH_SERVICE_HOST}/api/auth/.well-known/jwt-public-key

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        spring.cloud.gateway.requests: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG