spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "https://quingo.arhr.tech"
                  - "https://docs-quingo.arhr.tech"
                  - "http://localhost"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders:
                  - "*"
                allowCredentials: true
                maxAge: 3600
          routes:
            - id: auth-route
              uri: http://${AUTH_SERVICE_HOST}
              predicates:
                - Path=/api/auth/**

            - id: quizzes-route
              uri: http://${MAIN_SERVICE_HOST}
              predicates:
                - Path=/api/quizzes/**

            - id: users-route
              uri: http://${MAIN_SERVICE_HOST}
              predicates:
                - Path=/api/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG