apiVersion: apps/v1
kind: Deployment
metadata:
  name: quingo-gateway-deployment
  namespace: quingo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quingo-gateway
  template:
    metadata:
      labels:
        app: quingo-gateway
    spec:
      containers:
        - name: gateway-container
          image: artem5252/quingo-gateway:latest
          env:
            - name: MAIN_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: MAIN_SERVICE_HOST
            - name: AUTH_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: AUTH_SERVICE_HOST
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: CORS_ALLOWED_ORIGINS
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 8080